from setuptools import find_packages, setup

INSTALL_REQUIRES = [
    "hydra-core>=1.2.0",
    "mujoco-python-viewer",
    "rich",
    "ipdb",
    "matplotlib",
    "termcolor",
    "plotly",
    "loguru",
    "meshcat",
    "pynput",
    "scipy",
    "onnx",
    "onnxruntime",
    "opencv-python",
    "joblib",
    "easydict",
    "lxml",
    "lightning",
    "swanlab",
    "numpy-stl",
    "open3d",
    "toolz",
    "typer",
    "dm_control",
    "loop_rate_limiters",
    "mink",
    "quadprog",
    "einops",
    "prettytable",
    "tqdm",
    "tyro>=0.10.0a5",
    "torch>=2.7.0",
    "warp-lang",
    "mujoco-warp",
    "mujoco>=3.3.7",
    "trimesh>=4.8.3",
    "viser>=1.0.15",
    "moviepy",
    "tensordict",
    "rsl-rl-lib",
    "tensorboard>=2.20.0",  
    "onnxscript>=0.5.4",
    "wandb>=0.22.3",         
]

setup(
    name="clot_mjlab",
    version="0.1.0",
    license="MIT",

    packages=find_packages(include=["humanoidverse*", "mjlab*"]) + ["isaac_utils"],
    package_dir={
        "isaac_utils": "humanoidverse/isaac_utils/isaac_utils",
    },
    description="CLOT + MjLab",
    python_requires=">=3.10,<3.14",
    install_requires=INSTALL_REQUIRES,
)
